### ISSUE TITLE
error when trying to run default command

### ISSUE THREAD

**Issue by dinvisible1** [ej52/proxmox-scripts#1]
`curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s`

returns the following

```
[warn] Container will be created using the following settings.
[warn] 
[warn] ctid:     119
[warn] hostname: npm
[warn] cores:    1
[warn] memory:   512
[warn] swap:     0
[warn] disksize: 2G
[warn] bridge:   vmbr0
[warn] storage:  local-lvm
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...


[info] Updating LXC template list...
[info] Downloading LXC template...
[info] Allocating storage for LXC container...
[info] Creating LXC container...
[error] A problem occured while creating LXC container.
```

**Comment by dinvisible1** [comment]
> `curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s`
> 
> returns the following
> 
> ```
> [warn] Container will be created using the following settings.
> [warn] 
> [warn] ctid:     119
> [warn] hostname: npm
> [warn] cores:    1
> [warn] memory:   512
> [warn] swap:     0
> [warn] disksize: 2G
> [warn] bridge:   vmbr0
> [warn] storage:  local-lvm
> [warn] 
> [warn] If you want to abort, hit ctrl+c within 10 seconds...
> 
> 
> [info] Updating LXC template list...
> [info] Downloading LXC template...
> [info] Allocating storage for LXC container...
> [info] Creating LXC container...
> [error] A problem occured while creating LXC container.
> ```

So i did and update on the proxmox from 6.0-12 to 6.2-15 and got the following

```
root@node1:~# curl -sL https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/create.sh | bash -s

[warn] Container will be created using the following settings.
[warn] 
[warn] ctid:     105
[warn] hostname: npm
[warn] cores:    1
[warn] memory:   512
[warn] swap:     0
[warn] disksize: 2G
[warn] bridge:   vmbr0
[warn] storage:  local-lvm
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...

[info] Updating LXC template list...
[info] Downloading LXC template...
[info] Allocating storage for LXC container...
[info] Creating LXC container...
[info] Setting up LXC container...
wget: bad address 'raw.githubusercontent.com'
[info] Successfully created Nginx Proxy Manager LXC 105.


Nginx Proxy Manager is reachable by going to the following URL.

      http://:81


root@node1:~# 
```

**Comment by ej52** [comment]
@dinvisible1 

> [info] Creating LXC container...
[error] A problem occured while creating LXC container.

This was likely due to **6.0-12** missing some `pct create` parameters that are being used. 

> [info] Setting up LXC container...
wget: bad address 'raw.githubusercontent.com'
[info] Successfully created Nginx Proxy Manager LXC 105.

Looks like the container does not have internet access, how is your networking setup?

The default settings for `create.sh` assumes you are running a default proxmox setup where `vmbr0` is [bridged](https://pve.proxmox.com/wiki/Network_Configuration)

**Comment by shumancw** [comment]
I'm getting the following error when running the script. Any ideas?

> [info] Updating LXC template list...
> [info] Downloading LXC template...
> [error] 137 NULL: _storage_type=$(pvesm status -storage $_storage 2>/dev/null | awk 'NR>1 {print $2}')

Oh, thanks for the script!
