### ISSUE TITLE
Breaks after setting static IP

### ISSUE THREAD

**Issue by nodrogneirbo** [ej52/proxmox-scripts#10]
Hi

Great script - wish I had tried before losing the will to live with Rancher.

It installed fine and I could log in and set my admin account details etc.
I then realised the container was using DHCP so I changed the IP of the container in Proxmox from DHCP to a static IP. To my surprise this did not change the IP of the container. After many reboots. It showed the static in the alpine network config but did not apply. The only way I could get the new IP address to stick was to rename the interface from eth0 to eth1

I now get the NPM login screen but get the dreaded "bad gateway" error when trying to sign in.

Is there a preferred way to switch from DHCP to a static without breaking NPM?

[Follow up]
I thought a solution around this issue would be to install a standard Alpine LXC with the correct networking first then run the setup script rather than the create script.
Networking was confirmed working fine with the static IP but when I ran setup it seems to have modified Eth0 to DHCP again, despite /etc/network/interfaces showing my original static IP.

thanks
Gordon

**Comment by ej52** [comment]
@nodrogneirbo Apologies, I pushed some changes without fulling testing last time.

This issue should be fixed now, thanks to the following commit https://github.com/ej52/proxmox-scripts/commit/70038bf74a9c1ecaf06ed25e9fe95359902f1af9

**Comment by netstx** [comment]
I noticed this issue a day or two ago where I tried to upgrade NPM and it failed on udhcpc when npm was starting. Thanks for the fix!

**Comment by nodrogneirbo** [comment]
> @nodrogneirbo Apologies, I pushed some changes without fully testing last time.
> 
> This issue should be fixed now, thanks to the following commit [70038bf](https://github.com/ej52/proxmox-scripts/commit/70038bf74a9c1ecaf06ed25e9fe95359902f1af9)

Thanks for the speedy fix Elton. I will try the update later.

**Comment by nodrogneirbo** [comment]
I've just tried to use the create script to build a new NPM container to test and it seems that is broke now:

```
curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s -- --id 372 --storage SSD1-10GbE
[warn] Container will be created using the following settings.
[warn] 
[warn] ctid:     372
[warn] hostname: nginx-proxy-manager
[warn] cores:    1
[warn] memory:   512
[warn] swap:     0
[warn] disksize: 2G
[warn] bridge:   vmbr0
[warn] storage:  SSD1-10GbE
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...

[info] Updating LXC template list...
[info] Downloading LXC template...
[info] Allocating storage for LXC container...
[info] Creating LXC container...
[info] Setting up LXC container...
wget: bad address 'raw.githubusercontent.com'
[info] Successfully created Nginx Proxy Manager LXC 372.


Nginx Proxy Manager is reachable by going to the following URL.

      http://:81
```

**Comment by ej52** [comment]
@nodrogneirbo `wget: bad address 'raw.githubusercontent.com'` indicates a DNS/connectivity issue within the container.

Do your other containers have internet?

**Comment by nodrogneirbo** [comment]
They do have internet access. I have tried again just now and it worked perfectly so just a glitch I guess.
Thanks @ej52
