### ISSUE TITLE
Communication with the API failed, is NPM running correctly?

### ISSUE THREAD

**Issue by gcraenen** [ej52/proxmox-scripts#102]
After installation in a Proxmox environment (7.2) the LXC starts and works. I can login, but when I try to add letsencrypt certificates via Cloudflare and I first try to resolve the domainname before doing anything else I get: "Communication with the API failed, is NPM running correctly?"

If I proceed and add the DNS email and API token I just get a "Bad Gateway" error.

Should be working fine, since the same creds have been used for the Proxmox letsencrypt certificates and a Traefik letsencrypt environment. Both work fine.

**Comment by hareenpatel14** [comment]
Has anyone found a solution to this? i am running into the same issue here where i am unable to grab certs due to "is npm running"

**Comment by lighthousebulb** [comment]
Maybe the same problem here...

I found some interesting hints in the letsencrypt-log-file:

```
Certbot failed to authenticate some domains (authenticator: webroot). The Certificate Authority reported these problems:
  Domain: XXXXX
  Type:   connection
  Detail: XXX.XXX.XXX.XXX: Fetching https://XXX/.well-known/acme-challenge/XXX-XXX_XXX-XXX: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to download the temporary challenge files created by Certbot. Ensure that the listed domains serve their content from the provided --webroot-path/-w and that files created there can be downloaded from the internet.
```
The "/data/logs/proxy-host-1_access.log" is registering the hits from the Let's Encrypt validation server.
I don't know if that is the right behavior.

**Comment by GLehnhoff** [comment]
I have the same problem and access to my host does not work. I use a dyndns domain. Is that the reason?

**Comment by chriszuercher** [comment]
I'm facing the same issue. Is tis a configuration issue somewhere? I could create a certificate once, but updates are failing with the error mentioned.
