### ISSUE TITLE
Building frontend failed: "Tapable.plugin is deprecated. Use new API on `.hooks` instead"

### ISSUE THREAD

**Issue by GravitaBB** [ej52/proxmox-scripts#103]
**Script**
nginx-proxy-manager

**Describe the bug**
[error] Building frontend
/tmp/npm_install.sh: line 181: yarn build

**System info:**
 - Proxmox Version: 7.3-3
 - Alpine Version: 3.17

**Screenshots**
![image](https://user-images.githubusercontent.com/109347641/209222050-d9409757-36ab-4628-9587-709bbeedabee.png)

**Additional context**
Edit: in Debian 11 (VMware VM) the build/installation process runs just fine without any errors

**Comment by pegasusict** [comment]
same issue

**Comment by ParaVirtual** [comment]
Same issue here. Version of Alpine is 3.17, running on Proxmox VE 7.3-6

`[success] Checking for latest openresty repository
[success] Updating container OS
[success] Installing dependencies
[success] Setting up python
[success] Checking for latest NPM release
[success] Downloading NPM v2.9.20
[success] Setting up enviroment
[success] Generating dummy SSL certificate
[error] Building frontend
/tmp/npm_install.sh: line 181: yarn build
Tapable.plugin is deprecated. Use new API on `.hooks` instead
`node --trace-deprecation ...` to show where the warning was created)
unsupported
19)
10)
53)
16)
10)
5
12
3
10)
10)
3
11)
2)
4)
16)
9
16
3)
unsupported
19)
10)
53)
16)
10)
5
12
3
10)
10)
3
11)
2)
4)
16)
9
16
3)
71
 this[kHandle] = new _Hash(algorithm, xofLen);
                 ^

unsupported
19)
10)
53)
16)
10)
5
12
3
10)
10)
3
13)
{
error' ],
'digital envelope routines',
'unsupported',
'ERR_OSSL_EVP_UNSUPPORTED'
}

v18.14.2
Command failed with exit code 1.
/ #`

**Comment by heriniaina** [comment]
Same,

I think I'll install Alpine 3.16 since that's what he uses in the create.sh

**Comment by GravitaBB** [comment]
> I think I'll install Alpine 3.16 since that's what he uses in the create.sh

Seems to be working. I spun up a test container with Alpine 3.16 and it ran through without any issues.
Why haven't I thought about doing _this_ earlier? 🤣

**Comment by GravitaBB** [comment]
(Closed by accident -> reopened)

**Comment by heriniaina** [comment]
Confirmed, working well with Alpine 3.16 

So AFAIK it doesn't support Alpine 3.17 yet
