### ISSUE TITLE
Unable to login (Bad Gateway)

### ISSUE THREAD

**Issue by tarimpa** [ej52/proxmox-scripts#104]
**Script**
nginx-proxy-manager

**Describe the bug**
Unable to login, get "Bad Gateway" error message

**System info:**
 - Proxmox Version: 7.3-6
 - Alpine Version: 3.17.2

**Screenshots**

![image](https://user-images.githubusercontent.com/125159157/218282113-e9fd713e-d6f0-4854-8cf1-00c2989872ed.png)

**Additional context**

I have tried to upgrade with the setup.sh script again but got the same error that #103 
So I am unable to use Nginx Proxy Manager 
Can someone help me please ?

**Comment by Noztromo77** [comment]
I am getting the same error

**System info:**
- Proxmox Version: 7.2-3
- Debian GNU/Linux 10 (buster) (LXC)
- Installation on a existing debian 10 lxc
- Nginx Proxy Manager (NPM) v2.9.19
 
**Describe the bug**
At first I installed using the installation script that creates the LHK container and got an error after rebooting.
After that, I decided to try installing it again through the "alternative usage".
My actions:
1. Installed the Debian 10 LXC
2. Updated Debian and installed NPM
3. Made a live backup LXC
4. Logged into NPM with a standard username and password
5. Changed the login and password.
6. Uploaded my hosts and got certificates (everything worked fine).
7. After 12-16 hours, I tried to login to npm to change my hosts, but got "Bad Gateway" on login.
8. Restored the LXC container from backup and repeated step 4-6
9. Turned off the container and made a backup to restore it with my login password and hosts.
10. Turned on the container, tried to enter but immediately received "Bad gateway" at the entrance.

ps. sorry my english can be bad

**Comment by ParaVirtual** [comment]
I have got this error on a fresh, error-free install on an Alpine 3.16 LXC Container on Proxmox 7.3-6

The very first login attempt using default credentials fails with "Bad Gateway"

**Comment by krzysztofsk** [comment]
Update node js to current version. It worked for me.
