### ISSUE TITLE
[v2.9.20] Bad Gateway

### ISSUE THREAD

**Issue by dhzl84** [ej52/proxmox-scripts#105]
**Script**
nginx-proxy-manager

**Describe the bug**
No matter if I upgrade fron v2.9.19 or do a fresh install I get the well known "Bad Gateway" error when trying to log in via the webinterface.

**System info:**
 - Proxmox Version: 7.3-6
 - Debian Version: 11

**Screenshots**

**Comment by ignis-draco** [comment]
I have the same problem. 

The system log says that the **signals** module was not found. 

````
Mar 16 13:02:39 lxc-tmp systemd[1]: Starting Nginx Proxy Manager...
Mar 16 13:02:39 lxc-tmp systemd[1]: Started Nginx Proxy Manager.
Mar 16 13:02:39 lxc-tmp node[7028]: node:internal/modules/cjs/loader:1024
Mar 16 13:02:39 lxc-tmp node[7028]:   throw err;
Mar 16 13:02:39 lxc-tmp node[7028]:   ^
Mar 16 13:02:39 lxc-tmp node[7028]: Error: Cannot find module 'signale'
Mar 16 13:02:39 lxc-tmp node[7028]: Require stack:
Mar 16 13:02:39 lxc-tmp node[7028]: - /app/logger.js
Mar 16 13:02:39 lxc-tmp node[7028]: - /app/index.js
Mar 16 13:02:39 lxc-tmp node[7028]:     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1021:15)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Function.Module._load (node:internal/modules/cjs/loader:866:27)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Module.require (node:internal/modules/cjs/loader:1093:19)
Mar 16 13:02:39 lxc-tmp node[7028]:     at require (node:internal/modules/cjs/helpers:108:18)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Object.<anonymous> (/app/logger.js:1:19)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Module._compile (node:internal/modules/cjs/loader:1191:14)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Module.load (node:internal/modules/cjs/loader:1069:32)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Function.Module._load (node:internal/modules/cjs/loader:904:12)
Mar 16 13:02:39 lxc-tmp node[7028]:     at Module.require (node:internal/modules/cjs/loader:1093:19) {
Mar 16 13:02:39 lxc-tmp node[7028]:   code: 'MODULE_NOT_FOUND',
Mar 16 13:02:39 lxc-tmp node[7028]:   requireStack: [ '/app/logger.js', '/app/index.js' ]
Mar 16 13:02:39 lxc-tmp node[7028]: }
Mar 16 13:02:39 lxc-tmp systemd[1]: npm.service: Main process exited, code=exited, status=1/FAILURE
Mar 16 13:02:39 lxc-tmp systemd[1]: npm.service: Failed with result 'exit-code'.
Mar 16 13:02:39 lxc-tmp systemd[1]: npm.service: Scheduled restart job, restart counter is at 1.
Mar 16 13:02:39 lxc-tmp systemd[1]: Stopped Nginx Proxy Manager.
````

an `npm install signals` says: 
````
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: nginx-proxy-manager@2.9.20
npm ERR! Found: knex@2.4.0
npm ERR! node_modules/knex
npm ERR!   knex@"^2.4.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer knex@"<0.95.0" from objection@2.2.16
npm ERR! node_modules/objection
npm ERR!   objection@"^2.2.16" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
````

unfortunately, I don't know npm well enough to fathom the problem here.

**Comment by ParaVirtual** [comment]
Looking further at the logs, it seems that signale being missing is a red herring. I fixed the signale issue (well, fudged it, but enough for that to no longer error) and now the major complain is that sqlite3 is missing.

This is also backed u by running any yarn command, which attempts to fix/rebuild missing dependencies each time, always failing on sqlite3


I've never used Alpine or yarn before trying to get this container setup going, so have insufficient knowledge to diagnose further.

**Comment by ignis-draco** [comment]
Good news with the new version (2.9.21) everything works again.

**Comment by dhzl84** [comment]
Confirmed

**Comment by ParaVirtual** [comment]
Fixed in nginx-proxy-manager (upstream);
https://github.com/NginxProxyManager/nginx-proxy-manager/commit/fec36834f7dbc2f1bfcbbfddf942939d564429a8



> Updated objection, knex, liquidjs, signale and sqlite3 packages
> - Changes for objection migration
> - Moved common access template code to an include
> - Fixed access rules configuration generation
>  [develop](https://github.com/NginxProxyManager/nginx-proxy-manager) ([#2703](https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2703))
>  [v2.9.21](https://github.com/NginxProxyManager/nginx-proxy-manager/releases/tag/v2.9.21)
> @[jc21](https://github.com/NginxProxyManager/nginx-proxy-manager/commits?author=jc21)
> jc21 committed yesterday
