### ISSUE TITLE
Admin Page of nginx not working

### ISSUE THREAD

**Issue by n4tiv0** [ej52/proxmox-scripts#107]
Script
../setup.sh

Bug description
After the successful completion of the installation of all modules present in the ../setup.sh script, nginx doesn't open the administration page at "http://nginx_ip:81".

System information:
Proxmox version: [7.4]
Runing VM: Container LXC ubuntu 22.04 and turnkey-core.

Additional context:

After successfully running the module installation script on the Proxmox server, it was expected that nginx would be available on port 81 for access to the administration page. However, when trying to access the "http://nginx_ip:81" address, the page does not open and a connection error occurs. It is worth noting that the server is functioning properly and did not present any issues before the installation of the modules. It is important to solve this problem, as the nginx administration page is essential for configuring and managing the server.

**Comment by hiatsu0** [comment]
I came across this same issue, the admin page is no longer available. But in my case it used to work for months, so I can only guess that it is the `unattended-upgrades` I had installed that upgraded something, breaking npm :(

Any ways to start troubleshooting, or should I simply reinstall?
