### ISSUE TITLE
Your Script does not work for me on VM on ESXI7 With Alpine

### ISSUE THREAD

**Issue by witzker** [ej52/proxmox-scripts#11]
Hi
I followed your perfect script on Proxmox ad described, and it worked perfect! 
THX!

Now I want to set up a reverse manager on ESXi 7 in an Alpine VM
I logged in with putty with root
and put in your command for not using a proxmox container 

Alternative Usage
If you are not using proxmox or want to install this on a existing Alpine box, you can run the setup script itself._

Pls see below:

```
revproxy:~# wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh
[info] Updating container OS...
ERROR: http://openresty.org/package/alpine/v3.13/main: No such file or directory
WARNING: Ignoring http://openresty.org/package/alpine/v3.13/main: No such file or directory
revproxy:~#
```

Where is the problem?
Am I doing something wrong?
Is something missing in my Alpine VM?

Pls. be so kind and help me get it running as before.
Many THX in advance

regards
Witzker

PS:
revproxy:~# cat /etc/alpine-release
3.13.4
I installed this image:
![image](https://user-images.githubusercontent.com/4120266/113454977-cecba080-9409-11eb-8421-c4f51961ac40.png)

 x86_64

**Comment by ej52** [comment]
@witzker it seems as though openresty does not have a package for alpine v3.13 yet https://openresty.org/package/alpine/.

You can try editing `/etc/apk/repositories` and change 
`http://openresty.org/package/alpine/v3.13/main` to `http://openresty.org/package/alpine/v3.12/main`

I am currently on holiday, but will cater for this issue when I get back ;)

**Comment by witzker** [comment]
THX for answering in Holiday
Yes ! There is no! for 3.13!

https://forum.openresty.us/d/6535-version-v313-for-alpine-linux

I tried as you recommanded 
http://openresty.org/package/alpine/v3.12/main
but the script stops again :(

I installed an 13.12 Alpine & your script worked Perfectly!
NRM is running so no hurry - THX

So we have to wait? Or is there another possibility?

Maybe when You'll be back its solved by OpenResty

THX for answering again &
enjoy your Holiday

**Comment by witzker** [comment]
Now the
http://openresty.org/package/alpine/v3.13/main
is online.

I did an Update of alpine: to 3.13 - all OK

As I got no answer here I tried to run the script again!

NOW everything is broken and all my services are not reachable over the internet!!

output when running the script:
```
reversemanager:~# wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh
[info] Updating container OS...
[info] Installing prerequisites...
[info] Stoping services...
[info] Cleaning old files...
[info] Downloading NPM v2.9.2...
[info] Building frontend...
[info] Initalizing backend...
reversemanager:~#
```
I would need Quick hepl NOW Pls.
THX
