### ISSUE TITLE
Port 81 not accessible and error on log 

### ISSUE THREAD

**Issue by iLucas3D** [ej52/proxmox-scripts#111]
Hello,

After a new installation, I have this problem in the logs:

avril 12 18:26:04 nginx systemd[1]: Reloading.
avril 12 18:26:04 nginx systemd[1]: Reloading.
avril 12 18:26:04 nginx systemd[1]: Reached target Network is Online.
avril 12 18:26:04 nginx systemd[1]: Starting The OpenResty Application Platform...
avril 12 18:26:04 nginx systemd[1]: Started The OpenResty Application Platform.
avril 12 18:28:30 nginx systemd[1]: Reloading.
avril 12 18:28:30 nginx systemd[1]: Reloading.
avril 12 18:28:30 nginx systemd[1]: Starting Nginx Proxy Manager...
avril 12 18:28:30 nginx systemd[1]: Started Nginx Proxy Manager.
avril 12 18:28:31 nginx node[6273]: [12/04/2023] [18:28:31] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
avril 12 18:28:31 nginx node[6273]: [12/04/2023] [18:28:31] [Global   ] › ℹ  info      Creating a new JWT key pair...
avril 12 18:28:43 nginx node[6273]: [12/04/2023] [18:28:43] [Global   ] › ℹ  info      Wrote JWT key pair to config file: /data/keys.json
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      Current database version: none
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] auth Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] user Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] user_permission Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] proxy_host Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] redirection_host Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] dead_host Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] stream Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] access_list Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] certificate Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] access_list_auth Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [initial-schema] audit_log Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [websockets] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [websockets] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [forward_host] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [forward_host] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [http2_support] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [http2_support] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [http2_support] redirection_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [http2_support] dead_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [forward_scheme] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [forward_scheme] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [disabled] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [disabled] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [disabled] redirection_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [disabled] dead_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [disabled] stream Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [custom_locations] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [custom_locations] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [hsts] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [hsts] proxy_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [hsts] redirection_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [hsts] dead_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [settings] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [settings] setting Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [access_list_client] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [access_list_client] access_list_client Table created
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [access_list_client] access_list Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [access_list_client_fix] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [access_list_client_fix] access_list Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [pass_auth] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [pass_auth] access_list Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [redirection_scheme] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [redirection_scheme] redirection_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [redirection_status_code] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [redirection_status_code] redirection_host Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [stream_domain] Migrating Up...
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [stream_domain] stream Table altered
avril 12 18:28:44 nginx node[6273]: [12/04/2023] [18:28:44] [Migrate  ] › ℹ  info      [stream_domain] Migrating Up...
avril 12 18:28:45 nginx node[6273]: [12/04/2023] [18:28:45] [Setup    ] › ℹ  info      Creating a new user: admin@example.com with password: changeme
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [Setup    ] › ℹ  info      Initial admin setup completed
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [Setup    ] › ℹ  info      Default settings added
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [Setup    ] › ℹ  info      Logrotate Timer initialized
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [Setup    ] › ℹ  info      Logrotate completed.
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
avril 12 18:28:46 nginx node[6273]: [12/04/2023] [18:28:46] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
avril 12 18:28:47 nginx node[6273]: [12/04/2023] [18:28:47] [Global   ] › ℹ  info      Backend PID 6273 listening on port 3000 ...
avril 12 18:28:48 nginx node[6273]: [12/04/2023] [18:28:48] [Nginx    ] › ℹ  info      Reloading Nginx
a_vril 12 18:28:48 nginx node[6273]: [12/04/2023] [18:28:48] [SSL      ] › ✖  error     Error: Command failed: /usr/sbin/nginx -s reload
avril 12 18:28:48 nginx node[6273]: nginx: [error] invalid PID number "" in "/run/nginx/nginx.pid"
avril 12 18:28:48 nginx node[6273]:     at ChildProcess.exithandler (node:child_process:402:12)
avril 12 18:28:48 nginx node[6273]:     at ChildProcess.emit (node:events:513:28)
avril 12 18:28:48 nginx node[6273]:     at maybeClose (node:internal/child_process:1100:16)
avril 12 18:28:48 nginx node[6273]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)_

**For information, I access the site on port 80 locally, but not the administration interface on port 81**

**Comment by iLucas3D** [comment]
For information
I made the command "systemctl restart openresty",
root@nginx:/home/lucas# systemctl restart openresty
(1 minute waiting, no prompt)

for 1 minute I was able to access the new page on port 80 and access the admin page, then cut and the rest failed here are the logs

░░ L'unité (unit) npm.service a terminé son démarrage, avec le résultat done.
avril 12 18:33:41 nginx node[6503]: [12/04/2023] [18:33:41] [Global   ] › ℹ  info      Using Sqlite: /data/database.sqlite
avril 12 18:33:42 nginx node[6503]: [12/04/2023] [18:33:42] [Migrate  ] › ℹ  info      Current database version: none
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [Setup    ] › ℹ  info      Logrotate Timer initialized
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [Setup    ] › ℹ  info      Logrotate completed.
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
avril 12 18:33:43 nginx node[6503]: [12/04/2023] [18:33:43] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [SSL      ] › ℹ  info      Let's Encrypt Renewal Timer initialized
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [IP Ranges] › ℹ  info      IP Ranges Renewal Timer initialized
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [Global   ] › ℹ  info      Backend PID 6503 listening on port 3000 ...
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [Nginx    ] › ℹ  info      Reloading Nginx
avril 12 18:33:44 nginx node[6503]: [12/04/2023] [18:33:44] [SSL      ] › ✖  error     Error: Command failed: /usr/sbin/nginx -s reload
avril 12 18:33:44 nginx node[6503]: nginx: [error] invalid PID number "" in "/run/nginx/nginx.pid"
avril 12 18:33:44 nginx node[6503]:     at ChildProcess.exithandler (node:child_process:402:12)
avril 12 18:33:44 nginx node[6503]:     at ChildProcess.emit (node:events:513:28)
avril 12 18:33:44 nginx node[6503]:     at maybeClose (node:internal/child_process:1100:16)
avril 12 18:33:44 nginx node[6503]:     at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
avril 12 18:36:47 nginx systemd[1]: Starting Cleanup of Temporary Directories...
░░ Subject: L'unité (unit) systemd-tmpfiles-clean.service a commencé à démarrer
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) systemd-tmpfiles-clean.service a commencé à démarrer.
avril 12 18:36:47 nginx systemd[1]: systemd-tmpfiles-clean.service: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit systemd-tmpfiles-clean.service has successfully entered the 'dead' state.
avril 12 18:36:47 nginx systemd[1]: Finished Cleanup of Temporary Directories.
░░ Subject: L'unité (unit) systemd-tmpfiles-clean.service a terminé son démarrage
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) systemd-tmpfiles-clean.service a terminé son démarrage, avec le résultat done.
avril 12 18:42:13 nginx systemd[1]: Stopping The OpenResty Application Platform...
░░ Subject: L'unité (unit) openresty.service a commencé à s'arrêter
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) openresty.service a commencé à s'arrêter.
avril 12 18:42:13 nginx systemd[1]: openresty.service: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit openresty.service has successfully entered the 'dead' state.
avril 12 18:42:13 nginx systemd[1]: Stopped The OpenResty Application Platform.
░░ Subject: L'unité (unit) openresty.service a terminé son arrêt
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) openresty.service a terminé son arrêt.
avril 12 18:42:13 nginx systemd[1]: Starting The OpenResty Application Platform...
░░ Subject: L'unité (unit) openresty.service a commencé à démarrer
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) openresty.service a commencé à démarrer.
avril 12 18:42:13 nginx systemd[1]: openresty.service: Can't open PID file /usr/local/openresty/nginx/logs/nginx.pid (yet?) after start: Operation not permitted
avril 12 18:43:43 nginx systemd[1]: openresty.service: start operation timed out. Terminating.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6537 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6538 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6539 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6540 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6541 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6542 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6538 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6540 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6542 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ The unit openresty.service has entered the 'failed' state with result 'timeout'.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Unit process 6538 (nginx) remains running after unit stopped.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Unit process 6540 (nginx) remains running after unit stopped.
avril 12 18:43:43 nginx systemd[1]: Failed to start The OpenResty Application Platform.
░░ Subject: L'unité (unit) openresty.service a échoué
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░ 
░░ L'unité (unit) openresty.service a échoué, avec le résultat failed.

root@nginx:/home/lucas# systemctl status openresty
● openresty.service - The OpenResty Application Platform
     Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Wed 2023-04-12 18:43:43 CEST; 3min 16s ago
    Process: 6534 ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 6535 ExecStart=/usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
        CPU: 658ms

avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6540 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6541 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6542 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6538 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6540 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Killing process 6542 (nginx) with signal SIGKILL.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Failed with result 'timeout'.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Unit process 6538 (nginx) remains running after unit stopped.
avril 12 18:43:43 nginx systemd[1]: openresty.service: Unit process 6540 (nginx) remains running after unit stopped.
avril 12 18:43:43 nginx systemd[1]: Failed to start The OpenResty Application Platform.

**Comment by vmbs** [comment]
You can try this: https://github.com/ej52/proxmox-scripts/issues/109#issuecomment-1507747342

**Comment by Alexis-BX** [comment]
Encountered this bug today on Debian. 

Don't know if it can help someone but here's what fixed it for me:
- `sudo vim /usr/local/openresty/nginx/conf/nginx.conf`
- Comment the line `pid ...;` (add `#` at the start)
- Change `user npm;` to `user root;`
- Save and exit
- `sudo systemctl restart openresty.service`
