### ISSUE TITLE
LXC Container generation fails with openresty failed to start

### ISSUE THREAD

**Issue by DjQuro** [ej52/proxmox-scripts#118]
**Script**
nginx-proxy-manager

**Describe the bug**
After running `curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s
` the below mentioned error occurs
**System info:**
 - Proxmox Version: 7.4-3
 - Alpine Version: Sorrry, I don't know

**Screenshots**
https://share-your-photo.com/6054c31801

**Additional context**
```
[error] Starting services
/tmp/npm_install.sh: line 250: rc-service openresty start
4
configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
openresty failed to start
[error] 195 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"
```

**Comment by florian30491** [comment]
> **Script** nginx-proxy-manager
> 
> **Describe the bug** After running `curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s ` the below mentioned error occurs **System info:**
> 
> * Proxmox Version: 7.4-3
> * Alpine Version: Sorrry, I don't know
> 
> **Screenshots** https://share-your-photo.com/6054c31801
> 
> **Additional context**
> 
> ```
> [error] Starting services
> /tmp/npm_install.sh: line 250: rc-service openresty start
> 4
> configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
> openresty failed to start
> [error] 195 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"
> ```

I am receiving the same error.

**Comment by cmseasy** [comment]
Same error here on Proxmox 7.4-3

**Comment by wylie39** [comment]
Same on 7.3-3

**Comment by Glitch3dPenguin** [comment]
I am also having this issue running Alpine 3.16 running on Proxmox 7.4-3

**Comment by ExCoderAtWork** [comment]
I am having the same exact issue.

**Comment by Glitch3dPenguin** [comment]
I got this working with these steps:
https://klabsdev.com/posts/NginxProxyManager/

**Comment by florian30491** [comment]
> I got this working with these steps: https://klabsdev.com/posts/NginxProxyManager/

Just works. Thanks for your help.

**Comment by MyCleverGirl** [comment]
> I got this working with these steps: https://klabsdev.com/posts/NginxProxyManager/

i got it install and working but when i reboot it dont work. no matter how many times i install it?

**Comment by jidehem92** [comment]
it's related to the nginx.pid file for some reason.
log into container, edit /usr/local/openresty/nginx/conf/nginx.conf and comment the line starting with pid like this : 
# pid /run/nginx/nginx.pid;

it works ok, even after reboot, but SSL certificates are not working proprely

**Comment by MoncefYabi** [comment]
> it's related to the nginx.pid file for some reason. log into container, edit /usr/local/openresty/nginx/conf/nginx.conf and comment the line starting with pid like this : # pid /run/nginx/nginx.pid;
> 
> it works ok, even after reboot, but SSL certificates are not working proprely


Thanks for providing this workaround. 
I can confirm this. I commented out `pid /run/nginx/nginx.pid;` and the proxy manager started  after I reboot the LXC container.
What did you mean with "but SSL certificates are not working proprely"?

**Comment by jidehem92** [comment]
certbot was failing with error mentionned here : https://community.letsencrypt.org/t/nginx-proxy-manager-and-cert/198147
I've found a workaround : edit /opt/certbot/pyvenv.cfg and change : 
include-system-site-packages = false
to
include-system-site-packages = true

**Comment by MyCleverGirl** [comment]
ugh every hour the domains disconnect then re-connect

**Comment by Glitch3dPenguin** [comment]
> it's related to the nginx.pid file for some reason.
> 
> log into container, edit /usr/local/openresty/nginx/conf/nginx.conf and comment the line starting with pid like this : 
> 
> \# pid /run/nginx/nginx.pid;
> 
> 
> 
> it works ok, even after reboot, but SSL certificates are not working proprely
> 
> 

I am going to edit my script to do this on install so that isn't an issue any longer. Thanks for pointing this out!

**Comment by DocDrydenn** [comment]
My findings:

The script creates the `/run/nginx/` folder, however by the time it reaches the end of the script to start the services, that `/run/nginx/` folder is missing. (unsure as to why/how, but it's not there)

After running the script, and letting it error out on the whole 'nginx.pid` stuff, I manually create the `/run/nginx/` folder and restart the services... they fire right up without issue.

**Comment by Glitch3dPenguin** [comment]
> it's related to the nginx.pid file for some reason. log into container, edit /usr/local/openresty/nginx/conf/nginx.conf and comment the line starting with pid like this : # pid /run/nginx/nginx.pid;
> 
> it works ok, even after reboot, but SSL certificates are not working proprely

I had to run a restart and ran into the same issue. After commenting out line 3 in /usr/local/openresty/nginx/conf/nginx.conf I no longer get the same error. Not sure why the script is removing the folder on reboot or on startup. Not sure why this happens but  regardless I did update my [post](https://klabsdev.com/posts/NginxProxyManager/).

**Comment by jennec** [comment]
The container is removed after this error occurs.  There is nothing to connect to or change to be able to work around this problem.

**Comment by jidehem92** [comment]
@jennec Follow this tutorial : https://klabsdev.com/posts/NginxProxyManager/  (Tested on proxmox 7.4.3 & alpine 3.16)

**Comment by DocDrydenn** [comment]
Again, I've tested and repeated this numerous times... however I don't know why it's happening.

`alphine.sh` @ line 142, the `/run/nginx/` folder is created, however, by the time it reaches line 250, the `/run/nginx/` folder is gone. This causes line 250 `runcmd rc-service openresty start` to fail.

1. Manually create the folder with `mkdir /run/nginx/`
2. Start `openresty` with `rc-service openresty start`
3. Restart `npm` with `rc-service npm restart`

Everything fires up like it should. 

Also, a reboot of the container also somehow removes the `/run/nginx/` folder, so you end up right back to where you were by running the install script. Just repeat the above three steps and it will fire up like it should.

This all stems around the missing `/run/nginx` folder.
