### ISSUE TITLE
[error] A problem occured while downloading the LXC template.

### ISSUE THREAD

**Issue by ianalexis** [ej52/proxmox-scripts#12]
Hello,
I'm getting the error "[error] A problem occurred while downloading the LXC template." but idk how to check why is this happening.
Is this happening to anyone else?
How can i track what is triggering this error?

Thanks.
Rgrds.-

**Comment by thgeese** [comment]
has the same problem

**Comment by thgeese** [comment]
found the problem in line 177 pct create $_ctid "local:vztmpl/$_template" ${_pct_options[@]} &>/dev/null \  the Scripts need the local template storage. After assign the rule TEMPLATE to the LOCAL storage the script works for me

**Comment by ej52** [comment]
@ianalexis @thgeese I have added a new `--templates` command-line argument that can be set to override **local** storage.

**Comment by ianalexis** [comment]
Did it but getting the same, do i need to download any specific template before running the scrip? Thanks
[warn] Container will be created using the following settings.
[warn] 
[warn] ctid:     200
[warn] hostname: ct-nginx-proxy-manager
[warn] cores:    1
[warn] memory:   512
[warn] swap:     0
[warn] disksize: 2G
[warn] bridge:   vmbr0
[warn] storage:  local-lvm
[warn] templates:  /Pool2TB/ISO/dump
[warn] 
[warn] If you want to abort, hit ctrl+c within 10 seconds...

[info] Updating LXC template list...
[info] Downloading LXC template...
[error] A problem occured while downloading the LXC template.

**Comment by ej52** [comment]
@ianalexis You need to set `--templates` argument to the storage ID, not the path of where templates are stored

<img width="839" alt="Screenshot 2021-04-29 at 09 31 37" src="https://user-images.githubusercontent.com/6298706/116516386-d9286f80-a8cd-11eb-8685-b8f8eb182654.png">
