### ISSUE TITLE
I run the script for update now does not start

### ISSUE THREAD

**Issue by witzker** [ej52/proxmox-scripts#129]
As I'm not clever with all this server stuff, i don't know how to solve this:

![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/56b7cbfb-e7ad-4929-a6d7-d9c0ee94bfc0)
 when I start the server:
![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/1c34e044-9aa8-4a68-a7a7-22e401349fc2)

when i Goto: http://192.168.178.100:81/
![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/e4980250-2b33-42f3-abcb-5625bb1801a6)

Ps. help to get this back and running, as it is the heart of my tiny home lab.
Many THX

**Comment by Krafting** [comment]
Seems like there is an issue here, after updating mine (apk upgrade) (which is running for about a year) it seems that the website config got erased after updating the lxc, the only package that got updated was openresty, and If I go to <ip>:80 I'm on a default openresty page, normally you should be on the NPM default page.

Could you test that to see if it is the same issue here?

**Comment by witzker** [comment]
> and If I go to :80
![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/3c96f9f2-619c-4fb4-9cab-ef6b24eaa2b9)
 but ist it :81 for the NPM default page.

**Comment by witzker** [comment]
What's the matter here?
How can I solve the issue.
Any Help Pls.

**Comment by ahrasis** [comment]
If you read similar issues here, you will find that to solve them, you have to try:
(1) Running in the command line:
useradd -s /bin/false nginx
useradd -s /bin/false npm
(2) Then run the script again.
(3) Open and comment out line #3 in /usr/local/openresty/nginx/conf/nginx.conf 
#pid /run/nginx/nginx.pid;
(4) Save and exit the above file. Then restart openresty:
systemctl start openresty
(5) Try to open it again in your browser.
