### ISSUE TITLE
Can't connect to ip of container

### ISSUE THREAD

**Issue by lightsout** [ej52/proxmox-scripts#13]
I installed this script in Proxmox, it said it was successful and gave me the ip to login at. 
When I go to the ip on my local network nothing loads. I can access the container through 
the console of the proxmox webui so I can at least see that it is running. Is there something more
that I need to do. (I am a linux beginner if that wasn't obvious)

**Comment by netstx** [comment]
Can you check that sshd is installed/running? 

Otherwise you can set it up yourself: https://wiki.alpinelinux.org/wiki/Setting_up_a_ssh-server

**Comment by lightsout** [comment]
> 
> 
> Can you check that sshd is installed/running?
> 
> Otherwise you can set it up yourself: https://wiki.alpinelinux.org/wiki/Setting_up_a_ssh-server
> 
> EDIT: I think I misunderstood your question, did you mean you cannot access the Nginx Proxy Manager web page? The admin console is on port 81.

Yeah sorry I cannot access the admin page through port 81, "unable to connect".

**Comment by lightsout** [comment]
> 
> 
> Can you check that sshd is installed/running?
> 
> Otherwise you can set it up yourself: https://wiki.alpinelinux.org/wiki/Setting_up_a_ssh-server
> 
> EDIT: I think I misunderstood your question, did you mean you cannot access the Nginx Proxy Manager web page? The admin console is on port 81.

I installed SSH, can't login because it wants credentials. But when I type rc-status should I see nginx listed?
All I see is sshd, cron , networking.

**Comment by netstx** [comment]
NPM might not be running, did the install script issue any errors?

Try "ps aux" and see if openresty is running

**Comment by lightsout** [comment]
> 
> 
> NPM might not be running, did the install script issue any errors?
> 
> Try "ps aux" and see if openresty is running

Didn't notice any errors

**Comment by lightsout** [comment]
Just ran it again (the script) here is what I got and I cannot connect to this one either.
`[info] Updating LXC template list...
[info] Downloading LXC template...
[info] Allocating storage for LXC container...
[info] Creating LXC container...
[info] Setting up LXC container...
wget: bad address 'raw.githubusercontent.com'
[info] Successfully created Nginx Proxy Manager LXC 109.


Nginx Proxy Manager is reachable by going to the following URL.

      http://192.168.1.92:81`

**Comment by netstx** [comment]
You have an error: wget: bad address 'raw.githubusercontent.com'

Try creating the Alpine container manually using Proxmox, then run just the installation script.

**Comment by lightsout** [comment]
> 
> 
> You have an error: wget: bad address 'raw.githubusercontent.com'
> 
> Try creating the Alpine container manually using Proxmox, then run just the installation script.

Ok did that, here is what I get after installing curl and attempting the script

`-ash: bash: not found`

**Comment by lightsout** [comment]
Sorry for the ignorance, used the script at the bottom of the page and she's up and running. Thanks for the help.

**Comment by netstx** [comment]
No problem @lightsout

**Comment by ej52** [comment]
@lightsout This network-related issue has been logged a few times without proper feedback, #1, #2.

`wget: bad address 'raw.githubusercontent.com'`

This indicates that the container cannot resolve **raw.githubusercontent.com** via your DNS server on the initial setup.
Do you mind giving some insight as to how your networking is setup?

**Comment by Homer-Sim** [comment]
Sorry for writing here, but I have the same issue.
fresh LXC install (tried both ubuntu 22 and Debian 10 template) 
and the WGUI is not accessable via http:// 192.168.100.120:81
I did as you wrote a new start of the script and received this error:

[success] Cleaning old files
[error] Installing dependencies
/tmp/npm_install.sh: line 74: 'apt-get install -y --no-install-recommends $DEVDEPS gnupg openssl ca-certificates apache2-utils logrotate'
Sub-process /usr/bin/dpkg returned an error code (1)
