### ISSUE TITLE
Script does not work on Alpine 3.18.2

### ISSUE THREAD

**Issue by witzker** [ej52/proxmox-scripts#131]
**Script**
nginx-proxy-manager

![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/d6e3ecb0-8f9c-463d-8250-097ece476c67)

**Describe the bug**
started Install script for fresh Alpine - result:

![grafik](https://github.com/ej52/proxmox-scripts/assets/4120266/11ded8fa-dba3-49bf-91f4-69ca93db5c06)

**System info:**
 Fresh alpine NO - Proxmox 
 - Alpine Version: 3.18.2

**Screenshots**

**Additional context**

Can this script be updated To work on 3.18.2
or what is the latest version of Alpine, where the script worked?
Pls help
THX

**Comment by Eeems** [comment]
This probably duplicates #126

**Comment by craeckor** [comment]
My friend still had Alpine 3.16 as an option for templates.
I uploaded the template to my CDN just in case it gets deleted: [https://cdn1.craeckor.ch/data/alpine-3.16-default_20220622_amd64.tar.xz](https://cdn1.craeckor.ch/data/alpine-3.16-default_20220622_amd64.tar.xz)
