### ISSUE TITLE
apline 3.16 not found Proxmox 8

### ISSUE THREAD

**Issue by robbanl** [ej52/proxmox-scripts#139]
Alpine 3.16 not found when using Proxmox 8, had to manually change it to 3.18

**Comment by craeckor** [comment]
My friend still had Alpine 3.16 as an option for templates.
I uploaded the template to my CDN just in case it gets deleted: [https://cdn1.craeckor.ch/data/alpine-3.16-default_20220622_amd64.tar.xz](https://cdn1.craeckor.ch/data/alpine-3.16-default_20220622_amd64.tar.xz)

**Comment by dennyreiter** [comment]
I changed it to 3.18 also, but now it fails on installation:

`marionette.templatecache@1.0.0" has incorrect peer dependency "underscore@~1.8.3"`

Did it work OK for you?

**Comment by 15sharpie** [comment]
is there a fix for this yet?

**Comment by Eeems** [comment]
> is there a fix for this yet?

have you looked at the open PRs yet?
