### ISSUE TITLE
LXC setup error 

### ISSUE THREAD

**Issue by kkrautwald** [ej52/proxmox-scripts#14]
Trying to pull via 

curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s -- --bridge vmbr1 --storage nfs-fast --templates vm-backup

[info] Updating LXC template list...
[info] Downloading LXC template...
[info] Allocating storage for LXC container...
[info] Creating LXC container...
[info] Setting up LXC container...

[error] 194 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"

Any ideas why?

**Comment by ej52** [comment]
@kkrautwald Was a container created at all?
