### ISSUE TITLE
Script bug (?)

### ISSUE THREAD

**Issue by endyb66** [ej52/proxmox-scripts#148]
Environment:
Host: Proxmox 7.4-3
LXC: Debian 11.8

NPM is already running, trying to update with the install-script (alternative using).
Got this error after issuing the command:

```
~# sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox/main/install.sh)" -s --app nginx-proxy-manager
-s: 6: Syntax error: "(" unexpected
```

**Comment by ej52** [comment]
Fixed in the latest commit https://github.com/ej52/proxmox-scripts/commit/3a7cf2ed94cce923158b2470f805e720f30a745f

**Comment by endyb66** [comment]
I get another error

`/dev/fd/63: line 53: EPS_OS_NAME: unbound variable
`

**Comment by ej52** [comment]
Let's try again, new commit https://github.com/ej52/proxmox-scripts/commit/39b29f738b9e2bfc68c334d8db9519ee37a97e8d

**Comment by endyb66** [comment]
Okay this time the installation went through. Got some warnings however, I made some screenshots, hope it helps. Oh and I had to manually update the system / packages before using your script, otherwise the script stopped. So I did a

`apt-get update && apt-get upgrade && apt-get dist-upgrade && apt-get autoremove && apü-get autoclean`

![1](https://github.com/ej52/proxmox-scripts/assets/38163496/2bfa9e4d-2781-4a77-824d-12f38b79e3e4)
![2](https://github.com/ej52/proxmox-scripts/assets/38163496/ba7aa1c0-d6cb-417b-a282-a47747966c95)
![3](https://github.com/ej52/proxmox-scripts/assets/38163496/f27b2952-8008-42b3-8d1c-c9c52bbe7f27)

**Comment by ej52** [comment]
@endyb66 Good to hear, those warnings are just nodejs dependancies nothing to worry about.

What terminal/shell are you using? as the logging seems to be weird in the screenshots.

**Comment by endyb66** [comment]
> @endyb66 Good to hear, those warnings are just nodejs dependancies nothing to worry about.
> 
> What terminal/shell are you using? as the logging seems to be weird in the screenshots.
> 
> <img alt="Screenshot 2023-12-05 at 14 35 15" width="950" src="https://private-user-images.githubusercontent.com/6298706/288039892-628513e4-bcd4-42cc-86c0-48e1d02c0fc0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3ODAyODQsIm5iZiI6MTcwMTc3OTk4NCwicGF0aCI6Ii82Mjk4NzA2LzI4ODAzOTg5Mi02Mjg1MTNlNC1iY2Q0LTQyY2MtODZjMC00OGUxZDAyYzBmYzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDVUMTIzOTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA5NzUyZDk0ZjA4ZmZkN2YzYmYwODBkY2YzMGM2YTY5Y2JlMTU3MDdmOGIwMWVmNzAzYWM4YThmM2U4OGE0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LoQmyCPP8UZhG00CQRUZBh5etWVZs9AgRTe2E2sEjrs">

Alright perfect then!
I'm using putty on windows to connect to my Debian 11.8 Proxmox LXC

**Comment by megavenik** [comment]
hi! looks like you also need to fix it in setup.sh - https://github.com/ej52/proxmox-scripts/blob/39b29f738b9e2bfc68c334d8db9519ee37a97e8d/create.sh#L92

**Comment by ej52** [comment]
> hi! looks like you also need to fix it in setup.sh -
> 
> https://github.com/ej52/proxmox-scripts/blob/39b29f738b9e2bfc68c334d8db9519ee37a97e8d/create.sh#L92

Have moved `pms_check_os` for non CT install instead, as **create.sh** already does the check

**Comment by megavenik** [comment]
oh @ej52 , maybe we have some misunderstanding here, I'm trying to install n-p-m using `create.sh` as said in the README.md:

`bash -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox/main/create.sh)" -s --app nginx-proxy-manager --cleanup`

and it fails:

![изображение](https://github.com/ej52/proxmox-scripts/assets/815281/958d239c-fd33-46bc-9181-673968955c81)

should I avoid installing app directly from the `create.sh` as it is outdated?

**Comment by ej52** [comment]
@megavenik I just ran `create.sh` using the code from latest commit and that issue is no longer there. 
Could be a cache issue :/ You can try again other run the install script in the new container that was created with `create.sh`

**Comment by ej52** [comment]
I see you are actually running `create.sh` from a old commit, run the script from the main branch 
`bash -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox/main/create.sh)" -s --app nginx-proxy-manager --cleanup`

**Comment by megavenik** [comment]
yeah, I've tried the last commit mentioned in the https://github.com/ej52/proxmox-scripts/issues/148#issuecomment-1840544409 message) but now everything works fine! Thanks a lot for your work on scripts and sorry for disturbing)
