### ISSUE TITLE
Error on debian install

### ISSUE THREAD

**Issue by ketomagasaki** [ej52/proxmox-scripts#150]
**Script**
nginx-proxy-manager

**Describe the bug**
I launch the script with this command :

`bash -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox/main/create.sh)" -s --app nginx-proxy-manager --cleanup --id 1030 --storage vms --hostname CT-REVERSE-PROXY --os debian --bridge vmbr1`

And I get the following error :
```
✔ Using LXC template: debian-12-standard_12.2-1_amd64.tar.zst
✔ LXC container 1030 created successfully
bash: line 30: os_arch: command not found

[ERROR] on line 30 with exit code 127 while executing command EPS_OS_ARCH=$(os_arch)
```

**System info:**
 - Proxmox Version: 8.1.3
 - Debian Version: 12.2

**Screenshots**
![image](https://github.com/ej52/proxmox-scripts/assets/54591921/7aba7b4b-416e-490b-888a-b0401c2d198d)

Thank you for your help!

**Comment by ketomagasaki** [comment]
Same issue with Ubuntu:

![image](https://github.com/ej52/proxmox-scripts/assets/54591921/9abfd1ff-2cdf-4983-b0df-07f4adb9c467)

**Comment by ej52** [comment]
@ketomagasaki I had only tested on Proxmox 7, where everything works perfectly.

I just spun up a Proxmox 8 VM to test and I get the same error as you get, will look into it.
