### ISSUE TITLE
Update 2.10.4 to 2.11.0

### ISSUE THREAD

**Issue by ketomagasaki** [ej52/proxmox-scripts#160]
**Script**
nginx-proxy-manager
`sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox/main/install.sh)" -s --app nginx-proxy-manager`

**Describe the bug**
Following the release of version 2.11.0, I ran the script to update from version 2.10.4 to version 2.11.0, and I received this error message (see screenshot).

**System info:**
 - Proxmox Version: 8.1.4
 - Ubuntu Version: 22.04.3

**Screenshots**
![image](https://github.com/ej52/proxmox-scripts/assets/54591921/06b49869-b085-4ee0-832a-5839ca941a1f)

**Comment by samwathegreat** [comment]
I received a slightly different error referencing "sass-loader" -- Alpine linux 3.16

![image](https://github.com/ej52/proxmox-scripts/assets/4813336/30e4952f-3b17-42d1-b3e1-5b78bb8beb0e)

**Comment by programbo** [comment]
I just created a PR to fix this. https://github.com/ej52/proxmox-scripts/pull/161

**Comment by nick-perry14** [comment]
> I just created a PR to fix this. #161

Tried running this script (by modifying the outer install.sh to download this version)  Install works fine, but then I get a bad gateway error.  Any idea?

**Comment by programbo** [comment]
Maybe try modifying the create.sh to let the script create the VM and all the network settings?

**Comment by ketomagasaki** [comment]
I wanted to test, but I don't know how to launch a script in PR. I tried:
`sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/programbo/proxmox-scripts/bugfix/sed-replacing-dependency-version/apps/nginx-proxy-manager/install.sh)" -s --app nginx-proxy-manager`
or
`sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox-scripts/c703c0db69306f1b447beffcc89feae07c7d4e53/apps/nginx-proxy-manager/install.sh)" -s --app nginx-proxy-manager`

But it returns:
`Script loaded incorrectly!`

**Comment by nick-perry14** [comment]
> Maybe try modifying the create.sh to let the script create the VM and all the network settings?

Ended up being some issue with 2.11.0, so I ended up downgrading back to 2.10.4.



> I wanted to test, but I don't know how to launch a script in PR. I tried: `sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/programbo/proxmox-scripts/bugfix/sed-replacing-dependency-version/apps/nginx-proxy-manager/install.sh)" -s --app nginx-proxy-manager` or `sh -c "$(wget --no-cache -qO- https://raw.githubusercontent.com/ej52/proxmox-scripts/c703c0db69306f1b447beffcc89feae07c7d4e53/apps/nginx-proxy-manager/install.sh)" -s --app nginx-proxy-manager`
> 
> But it returns: `Script loaded incorrectly!`

As for this, you have to download the main install.sh, and then edit that to download the patched nginx install.sh

**Comment by ketomagasaki** [comment]
Hello,

I made a new attempt following PR #161, and it worked well. I just had to reconfigure the database in the configuration file and restart.

Thank you!

**Comment by samwathegreat** [comment]
> Hello,
> 
> I made a new attempt following PR #161, and it worked well. I just had to reconfigure the database in the configuration file and restart.
> 
> Thank you!

Curious what you needed to reconfigure.  I was able to successfully update after the fix was merged, and everything just worked.  There were some warnings about depreciated context in the .conf files, but everything still seems to be working fine.

**Comment by ketomagasaki** [comment]
I couldn't find documentation on using an external database, so I put the information directly into the /app/lib/config.js file. It's probably not the best approach, but I only found configurations for Docker.
