### ISSUE TITLE
Update after installation

### ISSUE THREAD

**Issue by zbuh** [ej52/proxmox-scripts#29]
How to update after using the script for installation?

**Comment by ej52** [comment]
@zbuh Currently the only way to update nginx-proxy-manager is to run the `setup.sh` script in the container

`wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh`

This will update all dependencies and nginx-proxy-manager while keeping your existing settings.

**Comment by NoBloodyABCorD** [comment]
When I try to update I get the following:
`[success] Stopping services
[success] Cleaning old files
[success] Removing old dependencies
[success] Checking for latest openresty repository
[success] Updating container OS
[success] Installing dependencies
[success] Setting up python
[success] Checking for latest NPM release
[success] Downloading NPM v2.9.9
[success] Setting up enviroment
[error] Building frontend
/tmp/npm_install.sh: line 181: yarn build
Tapable.plugin is deprecated. Use new API on `.hooks` instead
Command failed with signal "SIGKILL".
~ #`

**Comment by openaspace** [comment]
upgrading to the latest version on lxc container ... let's encrypt ssl creation report ERROR

**Comment by MrSuttonmann** [comment]
@ej52 Attempting an update today resulted in this error, any help would be greatly appreciated:
![2022-01-11 15_58_22-pve - Proxmox Virtual Environment](https://user-images.githubusercontent.com/7480500/148977155-45c4b76a-3a27-4ac1-b0f7-36326bde402d.png)

**Comment by Eeems** [comment]
> @ej52 Attempting an update today resulted in this error, any help would be greatly appreciated: ![2022-01-11 15_58_22-pve - Proxmox Virtual Environment](https://user-images.githubusercontent.com/7480500/148977155-45c4b76a-3a27-4ac1-b0f7-36326bde402d.png)

Did you mean to open a new issue?
