### ISSUE TITLE
Cannot install on Ubuntu

### ISSUE THREAD

**Issue by boutzamat** [ej52/proxmox-scripts#33]
**Script**
nginx-proxy-manager

**Describe the bug**
When i run the manual installation script: wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh

i get the following error: 

```
[success] Installing dependencies
[success] Installing python
[success] Installing openresty
[error] Installing nodejs
/tmp/npm_install.sh: line 69: apt-get update
85: apt-get update && apt-get install -y -q --no-install-recommends openresty
90: apt-get update && apt-get install -y -q --no-install-recommends nodejs
//deb.nodesource.com/setup_14.x
...
connected.
request sent, awaiting response... 200 OK
13764 (13K) [text/plain]
'STDOUT'

/tmp/npm_install.sh: line 37: printf: `M': invalid format character
    0K .......... ...                                        100root@npm:~# 
```

**System info:**
 - Proxmox Version: 6.4-6
 - Ubuntu Version: 21.04

**Screenshots**
![image](https://user-images.githubusercontent.com/4305046/126578428-0d6617bc-67a8-44aa-9230-b603b31c0595.png)

**Comment by ej52** [comment]
@boutzamat It seems openresty only has binaries for Ubuntu <= 20.04, will implement a check as I did with Alpine to use older binaries.

**Comment by boutzamat** [comment]
I am not familiar with Alpine but i will try it out. Thanks :)
