### ISSUE TITLE
[error] 137 NULL: _storage_type

### ISSUE THREAD

**Issue by shumancw** [ej52/proxmox-scripts#5]
I'm getting the following error when running the script. PVE is current with default repos. Any ideas?

> [info] Updating LXC template list...
> [info] Downloading LXC template...
> [error] 137 NULL: _storage_type=$(pvesm status -storage $_storage 2>/dev/null | awk 'NR>1 {print $2}')

> root@pve:~# pvesm status
> Name       Type       Status
> local       dir       active
> local-zfs      zfspool     active
> pve_iso            dir     active
> zoomzdisk1         dir     active
> zoomzstuff         dir     active

Oh, thanks for the script!

**Comment by shumancw** [comment]
Sorry, I needed to add `--storage local-zfs`

**Comment by ickam** [comment]
I get an error `bash: line 0: bash: local-zfs: invalid option name`

**Comment by ickam** [comment]
> I get an error `bash: line 0: bash: local-zfs: invalid option name`

https://github.com/ej52/proxmox-scripts/issues/50#issuecomment-907623305 actually fixes it
