### ISSUE TITLE
404 not found - when try to install nginx-proxy-manager in proxmox

### ISSUE THREAD

**Issue by kpleines** [ej52/proxmox-scripts#55]
**Script**
nginx-proxy-manager
https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh

**Describe the bug**
The script "https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh" which is used during the installation process can not find the dependend script "https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/install".
The called script ist missing. 

**System info:**
 - Proxmox Version: 7.0-8
 - Alpine Version: [e.g. 3.12]

**Screenshots**
Code from install Script:
`[info] Creating LXC container...
+ _pct_options=(-arch $_arch -cmode shell -hostname $_host_name -cores $_cpu_cores -memory $_memory -net0 name=eth0,bridge=$_bridge,ip=dhcp -onboot 1 -ostype $_os_type -rootfs $_rootfs,size=$_disk_size -storage $_storage -swap $_swap -tags npm)
+ pct create 101 local:vztmpl/alpine-3.12-default_20200823_amd64.tar.xz -arch amd64 -cmode shell -hostname nginx-proxy-manager -cores 1 -memory 512 -net0 name=eth0,bridge=vmbr0,ip=dhcp -onboot 1 -ostype alpine -rootfs local-lvm:vm-101-disk-0,size=2G -storage local-lvm -swap 0 -tags npm
+ cat
+ info 'Setting up LXC container...'
+ echo -e '\e[32m[info] Setting up LXC container...\e[39m'
[info] Setting up LXC container...
+ pct start 101
+ sleep 3
+ pct exec 101 -- sh -c 'wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh'
wget: can't connect to remote host (185.199.110.133): Connection refused
+ popd
+ rm -rf /tmp/tmp.q6KuRJCpdk
`

**Comment by ej52** [comment]
@kpleines I think whats happening here is that the container does not have internet connectivity,  please make sure you are using the correct `--bridge` for the setup
