### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by vdias** [ej52/proxmox-scripts#69]
[success] Checking for latest openresty repository
[success] Updating container OS
[success] Installing dependencies
[error] Setting up python
/tmp/npm_install.sh: line 100: pip3 install --no-cache-dir cffi certbot

/usr/bin/python3 /usr/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpuv08pvgn
/tmp/pip-install-5oax8c4e/cryptography_ad12ff45019b400898d635f06023b4b2

 running bdist_wheel
 running build
 running build_py
 running egg_info
 writing src/cryptography.egg-info/PKG-INFO
 writing dependency_links to src/cryptography.egg-info/dependency_links.txt
 writing requirements to src/cryptography.egg-info/requires.txt
 writing top-level names to src/cryptography.egg-info/top_level.txt
 reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
 reading manifest template 'MANIFEST.in'
 no previously-included directories found matching 'docs/_build'
no previously-included files found matching 'vectors'
no previously-included files matching '*' found under directory 'vectors'
no previously-included files matching '*' found under directory '.github'
no previously-included files found matching 'release.py'
no previously-included files found matching '.coveragerc'
no previously-included files found matching 'codecov.yml'
no previously-included files found matching '.readthedocs.yml'
no previously-included files found matching 'dev-requirements.txt'
no previously-included files found matching 'tox.ini'
no previously-included files found matching 'mypy.ini'
no previously-included files matching '*' found under directory '.zuul.d'
no previously-included files matching '*' found under directory '.zuul.playbooks'
 adding license file 'LICENSE'
 adding license file 'LICENSE.APACHE'
 adding license file 'LICENSE.BSD'
 adding license file 'LICENSE.PSF'
 running build_ext
 running build_rust

     =============================DEBUG ASSISTANCE=============================
     If you are seeing a compilation error please try the following steps to

     1) Upgrade to the latest pip and try again. This will fix errors for most
//pip.pypa.io/en/stable/installing/#upgrading-pip
for specific
        instructions for your platform.

//cryptography.io/en/latest/faq/

//cryptography.io/en/latest/installation/#rust

3.8.10
Linux-5.13.19-4-pve-x86_64-with
n/a
60.9.0
1.1.2
     =============================DEBUG ASSISTANCE=============================

can't find Rust compiler

 If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

     pip install --upgrade pip

 and then retry package installation.

is the recommended way to download and update the Rust compiler toolchain.
ta elbaliava( putsur ,ylevitanretlA .noitallatsni gnirud HTAP eht no si ti erusne dna reganam egakcap metsys ruoy morf relipmoc tsuR a gnillatsni yrt ,ecruos mor
is the recommended way to download and update the Rust compiler toolchai  This package requires Rust >=1.41.0.
ta elbaliava( putsur ,ylevitanretlA .noitallatsni gnirud HTAP eht no si ti erusne dna reganam egakcap metsys ruoy morf relipm  ----------------------------------------
Failed building wheel for cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
You are using pip version 21.1.1; however, version 22.0.3 is available.
Could not You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
 running build
 running build_py
 running egg_info
 writing src/cryptography.egg-info/PKG-INFO
 writing dependency_links to src/cryptography.egg-info/dependency_links.txt
 writing requirements to src/cryptography.egg-info/requires.txt
 writing top-level names to src/cryptography.egg-info/top_level.txt
 reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
 reading manifest template 'MANIFEST.in'
 no previously-included directories found matching 'docs/_build'
no previously-included files found matching 'vectors'
no previously-included files matching '*' found under directory 'vectors'
no previously-included files matching '*' found under directory '.github'
no previously-included files found matching 'release.py'
no previously-included files found matching '.coveragerc'
no previously-included files found matching 'codecov.yml'
no previously-included files found matching '.readthedocs.yml'
no previously-included files found matching 'dev-requirements.txt'
no previously-included files found matching 'tox.ini'
no previously-included files found matching 'mypy.ini'
no previously-included files matching '*' found under directory '.zuul.d'
no previously-included files matching '*' found under directory '.zuul.playbooks'
 adding license file 'LICENSE'
 adding license file 'LICENSE.APACHE'
 adding license file 'LICENSE.BSD'
 adding license file 'LICENSE.PSF'
 running build_ext
 running build_rust

     =============================DEBUG ASSISTANCE=============================
     If you are seeing a compilation error please try the following steps to

     1) Upgrade to the latest pip and try again. This will fix errors for most
//pip.pypa.io/en/stable/installing/#upgrading-pip
for specific
        instructions for your platform.

//cryptography.io/en/latest/faq/

//cryptography.io/en/latest/installation/#rust

3.8.10
Linux-5.13.19-4-pve-x86_64-with
n/a
60.9.0
1.1.2
     =============================DEBUG ASSISTANCE=============================

can't find Rust compiler

 If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

     pip install --upgrade pip

 and then retry package installation.

is the recommended way to download and update the Rust compiler toolchain.
ta elbaliava( putsur ,ylevitanretlA .noitallatsni gnirud HTAP eht no si ti erusne dna reganam egakcap metsys ruoy morf relipmoc tsuR a gnillatsni yrt ,ecruos mor
is the recommended way to download and update the Rust compiler toolchai  This package requires Rust >=1.41.0.
ta elbaliava( putsur ,ylevitanretlA .noitallatsni gnirud HTAP eht no si ti erusne dna reganam egakcap metsys ruoy morf relipm  ----------------------------------------
Failed building wheel for cryptography
Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
You are using pip version 21.1.1; however, version 22.0.3 is available.
Could not You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
[error] 195 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"

**Comment by BCurrell** [comment]
I forked the repo, removed the `clear`s and the ANSI escape codes as best I could so I could see the actual error without it being hidden:

```none
proxy-01:~# wget --no-cache -qO - https://raw.githubusercontent.com/BCurrell/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh
Connecting to raw.githubusercontent.com (185.199.108.133:443)
saving to '/tmp/npm_install.sh'
npm_install.sh       100% |*********************************************************************************************************************************************************************|  7480  0:00:00 ETA
'/tmp/npm_install.sh' saved
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch http://openresty.org/package/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.12.9-62-g8596bdad23 [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v3.12.9-58-g838b7dc4f5 [http://dl-cdn.alpinelinux.org/alpine/v3.12/community]
OK: 12865 distinct packages available
OK: 110 MiB in 65 packages
(1/21) Installing binutils (2.34-r2)
(2/21) Installing gmp (6.2.1-r1)
(3/21) Installing isl (0.18-r0)
(4/21) Installing libgomp (9.3.0-r2)
(5/21) Installing libatomic (9.3.0-r2)
(6/21) Installing libgphobos (9.3.0-r2)
(7/21) Installing mpfr4 (4.0.2-r4)
(8/21) Installing mpc1 (1.1.0-r1)
(9/21) Installing gcc (9.3.0-r2)
(10/21) Installing musl-dev (1.1.24-r10)
(11/21) Installing libc-dev (0.7.2-r3)
(12/21) Installing g++ (9.3.0-r2)
(13/21) Installing pcre2 (10.35-r0)
(14/21) Installing git (2.26.3-r0)
(15/21) Installing linux-headers (5.4.5-r1)
(16/21) Installing pkgconf (1.7.2-r0)
(17/21) Installing libffi-dev (3.3-r2)
(18/21) Installing make (4.3-r0)
(19/21) Installing npm (12.22.10-r0)
(20/21) Installing openssl-dev (1.1.1l-r0)
(21/21) Installing python3-dev (3.8.10-r0)
Executing busybox-1.31.1-r21.trigger
OK: 400 MiB in 86 packages
Looking in links: /tmp/tmpc84zwyda
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (56.0.0)
Requirement already satisfied: pip in /usr/lib/python3.8/site-packages (21.1.1)
Requirement already satisfied: cryptography==3.3.2 in /usr/lib/python3.8/site-packages (3.3.2)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.8/site-packages (from cryptography==3.3.2) (1.15.0)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python3.8/site-packages (from cryptography==3.3.2) (1.16.0)
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi>=1.12->cryptography==3.3.2) (2.21)
Requirement already satisfied: cffi in /usr/lib/python3.8/site-packages (1.15.0)
Collecting certbot
  Downloading certbot-1.23.0-py2.py3-none-any.whl (270 kB)
     |████████████████████████████████| 270 kB 3.5 MB/s 
Requirement already satisfied: pycparser in /usr/lib/python3.8/site-packages (from cffi) (2.21)
Requirement already satisfied: setuptools>=39.0.1 in /usr/lib/python3.8/site-packages (from certbot) (56.0.0)
Collecting pyrfc3339
  Downloading pyRFC3339-1.1-py2.py3-none-any.whl (5.7 kB)
Collecting josepy>=1.9.0
  Downloading josepy-1.12.0-py2.py3-none-any.whl (29 kB)
Collecting zope.component
  Downloading zope.component-5.0.1-py2.py3-none-any.whl (68 kB)
     |████████████████████████████████| 68 kB 8.7 MB/s 
Collecting parsedatetime>=2.4
  Downloading parsedatetime-2.6-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 9.6 MB/s 
Collecting zope.interface
  Downloading zope.interface-5.4.0.tar.gz (249 kB)
     |████████████████████████████████| 249 kB 7.5 MB/s 
Collecting configobj>=5.0.6
  Downloading configobj-5.0.6.tar.gz (33 kB)
Collecting distro>=1.0.1
  Downloading distro-1.7.0-py3-none-any.whl (20 kB)
Collecting acme>=1.23.0
  Downloading acme-1.23.0-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 9.3 MB/s 
Collecting pytz
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
     |████████████████████████████████| 503 kB 7.4 MB/s 
Collecting ConfigArgParse>=0.9.3
  Downloading ConfigArgParse-1.5.3-py3-none-any.whl (20 kB)
Requirement already satisfied: cryptography>=2.5.0 in /usr/lib/python3.8/site-packages (from certbot) (3.3.2)
Collecting requests>=2.14.2
  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)
     |████████████████████████████████| 63 kB 9.2 MB/s 
Collecting PyOpenSSL>=17.3.0
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)
     |████████████████████████████████| 55 kB 9.8 MB/s 
Collecting requests-toolbelt>=0.3.0
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 9.8 MB/s 
Requirement already satisfied: six in /usr/lib/python3.8/site-packages (from configobj>=5.0.6->certbot) (1.16.0)
Collecting cryptography>=2.5.0
  Downloading cryptography-36.0.1.tar.gz (572 kB)
     |████████████████████████████████| 572 kB 7.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     |████████████████████████████████| 149 kB 7.6 MB/s 
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     |████████████████████████████████| 138 kB 7.4 MB/s 
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 8.6 MB/s 
Collecting zope.hookable>=4.2.0
  Downloading zope.hookable-5.1.0.tar.gz (21 kB)
Collecting zope.event
  Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Using legacy 'setup.py install' for configobj, since package 'wheel' is not installed.
Using legacy 'setup.py install' for zope.hookable, since package 'wheel' is not installed.
Using legacy 'setup.py install' for zope.interface, since package 'wheel' is not installed.
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... error
```

The script runs absolutely fine on a Debian host, so I think this is an issue with the cryptography wheel on Alpine only.

**Comment by rroethof** [comment]
apk add py3-pip

should work too
