### ISSUE TITLE
Cannot install from script

### ISSUE THREAD

**Issue by BShurilla** [ej52/proxmox-scripts#74]
**Script**
nginx-proxy-manager

**Describe the bug**
Goes through the process, creates the container, starts working in the container, then gives this error:

`[error] 195 NULL: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"`

It then destroys the container.

**System info:**
 - Proxmox Version: 7.1-10

**Comment by olesk75** [comment]
Exactly the same bug stops me on a proxmox 7.0 server

**Comment by akic100** [comment]
I had the same problem on PE7.1-7. It boiled down to the setup script not having the rust compiler in PATH. I fixed it by editing the last line of create.sh:
`pct exec $_ctid -- sh -c "wget --no-cache -qO - https://sh.rustup.rs | sh; source $HOME/.cargo/env; wget --no-cache -qO - $_raw_base/setup.sh | sh"`
I'm sure there's a more proper way to do it but this worked for me.

**Comment by Joriempie** [comment]
> I had the same problem on PE7.1-7. It boiled down to the setup script not having the rust compiler in PATH. I fixed it by editing the last line of create.sh: `pct exec $_ctid -- sh -c "wget --no-cache -qO - https://sh.rustup.rs | sh; source $HOME/.cargo/env; wget --no-cache -qO - $_raw_base/setup.sh | sh"` I'm sure there's a more proper way to do it but this worked for me.

Thanks.

I ran:

1.  wget https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh
2. Edited the file: nano create.sh > and the latest line I edited as you suggested.
3. chmod +x create.sh
4. bash create.sh --id 105 --bridge vmbr0 --cores 2 --disksize 4G --hostname web01 --memory 512 --storage local-zfs --templates local
5. In the bash I pressed 1 (recommended option).

**Comment by dafinga** [comment]
> I had the same problem on PE7.1-7. It boiled down to the setup script not having the rust compiler in PATH. I fixed it by editing the last line of create.sh:
> `pct exec $_ctid -- sh -c "wget --no-cache -qO - https://sh.rustup.rs | sh; source $HOME/.cargo/env; wget --no-cache -qO - $_raw_base/setup.sh | sh"`
> I'm sure there's a more proper way to do it but this worked for me.

This is still an issue as of May 18th. downloading and manually editing the create.sh script per the instructions from akic100 worked a treat. LXC now up and running. FWIW mine is using 1.28GB of space...
