### ISSUE TITLE
Unable to login after update

### ISSUE THREAD

**Issue by taylor-mcdonald** [ej52/proxmox-scripts#76]
I used the command `wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh` to update my conatiner to v2.9.16.  NPM is working, but I can no longer log in.  The login screen is there, but hitting the sign in button doesn't do anything.  Rebooting the container did not help.

**Comment by MikeCaldera** [comment]
Email:    admin@example.com
Password: changeme

That will get you in. After that you probably made an incorrect password CAPS
All else fail try again...been there done that :)
