### ISSUE TITLE
on alpine 5.15.37-0-lts can't install yarn

### ISSUE THREAD

**Issue by openaspace** [ej52/proxmox-scripts#80]
**Script**
direct alpine install

**Describe the bug**
/tmp/npm_install.sh: line 92: 'apk add python3 openresty nodejs yarn openssl apache2-utils logrotate $DEVDEPS'
when executing the sh script.

and installing 'apk add python3 openresty nodejs yarn openssl apache2-utils logrotate $DEVDEPS'
report: 
**ERROR: unable to select packages:
  yarn (no such package):
    required by: world[yarn]**

**System info:**
 - Alpine Version: [5.15.37-0]

**Screenshots**

**Additional context**

**Comment by HellStorm666** [comment]
This can be fixed by editing /etc/apk/repositories

`apk add nano`
`nano /etc/apk/repositories`
uncommand (remove de #)  in front of the line that ends with v3.16/community
Save (crtl+x)
`apk update`

And re-run the script.
