### ISSUE TITLE
error: No LXC template found for alpine-3.12

### ISSUE THREAD

**Issue by rmfberlin** [ej52/proxmox-scripts#86]
In proxmox-VE 7.2-3 I tried to install nginx proxy manager with 
`curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s`

I got this error message:
`No LXC template found for alpine-3.12`
How can I resolve this?

**Comment by maxwnewcomer** [comment]
@rmfberlin first make sure you have a valid version of alpine installed (i have 3.16) in your local CT Templates. 
Then you can run 
`wget https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh`
`nano create.sh`
then, change _os_version to whatever version you have in CT Templates 
`_os_version = 3.16`
then exit, save.
Then, you give the .sh file permissions with 
`chmod +x create.sh`
After that you can 
`./create.sh`
and everything should start working!

Best of luck, let me know if you run into any trouble.

**Comment by daufinsyd** [comment]
I created a pull request with a fix if you want to download it. #85

**Comment by daufinsyd** [comment]
btw I changed to docker running inside LXC to keep it lightweight.
