### ISSUE TITLE
[error] Downloading NPM v.tar.gz

### ISSUE THREAD

**Issue by kainjinez** [ej52/proxmox-scripts#88]
```
[success] Checking for latest openresty repository
[success] Updating container OS
[success] Installing dependencies
[success] Setting up python
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 109: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'
Broken pipe
HTTP/1.1 404 Not Found
invalid magic
short read
[error] 195 ./create2.sh: pct exec $_ctid -- sh -c "wget --no-cache -qO - $_raw_base/setup.sh | sh"
```
I dig into a bit and see https://github.com/NginxProxyManager/nginx-proxy-manager/archive not found.

**Comment by gragragrab** [comment]
Hello. I have had the same problem.
The issue was with how the script grabs the version number of the release. 
Have a look at this fix, that did the work for me. #89

**Comment by kainjinez** [comment]
@gragragrab can you help with Alpine version? I did not familiar with debian or linux so I cannot convert changes.

**Comment by boldizsarszasz** [comment]
[success] Installing dependencies
[success] Installing python
[success] Installing openresty
[success] Installing nodejs
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now

Now I get stuck at line 113 where it tries to extract the latest version

**Comment by gragragrab** [comment]
> @gragragrab can you help with Alpine version? I did not familiar with debian or linux so I cannot convert changes.

I believe you could you the same approach.

**Comment by cyberdork33** [comment]
> 

I am not sure why, but the regex did not seem to work for me in the alpine script. It gave a broken pipe error. It did work in a debian container though just fine.

**Comment by vmbs** [comment]
I have the same error:

```
[success] Installing dependencies
[success] Installing python
[success] Installing openresty
[success] Installing nodejs
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now
```

**Comment by battaglin** [comment]
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now

error on: 
Debian 11
Ubuntu 20.04 + 22.04

**Comment by Martin-1182** [comment]
I have the same error:
```
[success] Installing dependencies
[success] Installing python
[success] Installing openresty
[success] Installing nodejs
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now
```

**Comment by cyberdork33** [comment]
> Hello. I have had the same problem. The issue was with how the script grabs the version number of the release. Have a look at this fix, that did the work for me. #89

gragragrab the -P argument of grep does not work on alpine. I think this will work though:
`_latest_version=$(basename $(cat ./_latest_release | grep -wo "expanded_assets/v.*\d") | cut -d'v' -f2)`

**Comment by vmbs** [comment]
> > Hello. I have had the same problem. The issue was with how the script grabs the version number of the release. Have a look at this fix, that did the work for me. #89
> 
> @gragragrab the -P argument of grep does not work on alpine. I think this will work though: `_latest_version=$(basename $(cat ./_latest_release | grep -wo "expanded_assets/v.*\d") | cut -d'v' -f2)`

This is not working in Ubuntu :(

**Comment by cyberdork33** [comment]
> This is not working in Ubuntu :(

In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.

**Comment by vmbs** [comment]
> > This is not working in Ubuntu :(
> 
> In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.

Sorry, Ubuntu container in debian.sh script

**Comment by cyberdork33** [comment]
> > In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.
> 
> 
> 
> Sorry, Ubuntu container in debian.sh script

Ok I will try to test in a bit. What are you doing to execute the script? Are you still getting the same error? Have you tried gragragrab's version (which did work for me in a debian container)?

**Comment by vmbs** [comment]
> > > In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.
> > 
> > 
> > Sorry, Ubuntu container in debian.sh script
> 
> Ok I will try to test in a bit. What are you doing to execute the script? Are you still getting the same error? Have you tried gragragrab's version (which did work for me in a debian container)?

I was testing this command:
`wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`
only I am changing the GITHUB with my GitLab where I have cloned the repo.
Also this is the continer:
`# lsb_release -dr
Description:	Ubuntu 20.04 LTS
Release:	20.04`

**Comment by cyberdork33** [comment]
> > > > In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.
> 
> > > 
> 
> > > 
> 
> > > Sorry, Ubuntu container in debian.sh script
> 
> > 
> 
> > Ok I will try to test in a bit. What are you doing to execute the script? Are you still getting the same error? Have you tried gragragrab's version (which did work for me in a debian container)?
> 
> 
> 
> I was testing this command:
> 
> `wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`
> 
> only I am changing the GITHUB with my GitLab where I have cloned the repo.
> 
> Also this is the continer:
> 
> `# lsb_release -dr
> 
> Description:	Ubuntu 20.04 LTS
> 
> Release:	20.04`

Ok that wget command is still pulling the script from this repo which has not been fixed. The setup.sh file will pull the Debian or alpine script (again from this repo) to the container and execute it there. You need to get the patched script in your container and execute that instead.

**Comment by gragragrab** [comment]
> > > > In an Ubuntu host or container? What I posted was mainly to patch the alpine.sh script. Gragragrab posted a patch for the debian.sh script (which also runs on Ubuntu containers). This issue is not related to the host OS that I can tell.
> > > 
> > > 
> > > Sorry, Ubuntu container in debian.sh script
> > 
> > 
> > Ok I will try to test in a bit. What are you doing to execute the script? Are you still getting the same error? Have you tried gragragrab's version (which did work for me in a debian container)?
> 
> I was testing this command: `wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh` only I am changing the GITHUB with my GitLab where I have cloned the repo. Also this is the continer: `# lsb_release -dr Description: Ubuntu 20.04 LTS Release: 20.04`

You should try to use the fixed script.
The fix for debian.sh is proposed by #89.

Either adopt the patch in your repo (preferred), or fork my repo (https://github.com/gragragrab/proxmox-scripts) and change ej52 username username to your username for the script to be able to run from your repo.

**Comment by cyberdork33** [comment]
OK i did a pull request to patch the alpine script also: https://github.com/ej52/proxmox-scripts/pull/91

**Comment by vmbs** [comment]
Thanks @cyberdork33 is working. I was changing in setup.sh with my user and is working from your repo.

**Comment by dressyspider** [comment]
I am also receiving this error.

**My configuration:**
Proxmox container
Debian 11

**Error:**
[success] Checking for latest NPM release
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now

**Comment by vmbs** [comment]
> I am also receiving this error.
> 
> **My configuration:** Proxmox container Debian 11
> 
> **Error:** [success] Checking for latest NPM release [error] Downloading NPM v.tar.gz /tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'
> 
> unexpected end of file Child returned status 1 exiting now

You can try my Fork:
` wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh `

**Comment by dMopp** [comment]
> > I am also receiving this error.
> > **My configuration:** Proxmox container Debian 11
> > **Error:** [success] Checking for latest NPM release [error] Downloading NPM v.tar.gz /tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'
> > unexpected end of file Child returned status 1 exiting now
> 
> @dressyspider You can try my Fork: `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`

Thanks, works with debian, too. 

btw: Howto upgrade the proxy manager? just npm upgrade ?

**Comment by kerkhra** [comment]
Hi,

> > I am also receiving this error.
> > **My configuration:** Proxmox container Debian 11
> > **Error:** [success] Checking for latest NPM release [error] Downloading NPM v.tar.gz /tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'
> > unexpected end of file Child returned status 1 exiting now
> 
> @dressyspider You can try my Fork: `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`

Thanks. This is works on debian and not on alpine.

**Comment by ETH-contractDev** [comment]
Has anyone tested this script? In terms of security, it works very strangely.

**Comment by draxalene** [comment]
Hello, 
For information, not work on a CT ubuntu 22.04. 
So i use CT Ubuntu 20.04

**Comment by jktikka** [comment]
So I used @vmbs fork code which worked `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh` But did not think about entering this in the proxmox shell instead of a new CT.

Can anyone advise on reversing the installation on the proxmox server? Thanks

**Comment by hosmancevic** [comment]
> wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh

i got the same issue...

**Comment by vmbs** [comment]
> > wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh
> 
> i got the same issue...

Just to clarify that my Fork works only with CT Ubuntu 20.04 which is already built, `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`  and not with AlpineOS. For AlpineOS I was using @cyberdork33 Fork: `wget --no-cache -qO - https://raw.githubusercontent.com/gragragrab/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`

**Comment by hosmancevic** [comment]
> > > wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh
> > 
> > 
> > i got the same issue...
> 
> Just to clarify that my Fork works only with CT Ubuntu 20.04 which is already built, `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh` and not with AlpineOS. For AlpineOS I was using @cyberdork33 Fork: `wget --no-cache -qO - https://raw.githubusercontent.com/gragragrab/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh`

Sorry i quoted the wrong reply, i istallled it on my node instead of a CT..

**Comment by vmbs** [comment]
> So I used @vmbs fork code which worked `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh` But did not think about entering this in the proxmox shell instead of a new CT.
> 
> Can anyone advise on reversing the installation on the proxmox server? Thanks

Sorry @jktikka, I don't have a method to reverse that, but you can look at the script `https://github.com/ej52/proxmox-scripts/blob/main/lxc/nginx-proxy-manager/install/debian.sh` and uninstall whatever the script is installing.

**Comment by hosmancevic** [comment]
> > So I used @vmbs fork code which worked `wget --no-cache -qO - https://raw.githubusercontent.com/vmbs/proxmox-scripts/main/lxc/nginx-proxy-manager/setup.sh | sh` But did not think about entering this in the proxmox shell instead of a new CT.
> > Can anyone advise on reversing the installation on the proxmox server? Thanks
> 
> Sorry @jktikka, I don't have a method to reverse that, but you can look at the script `https://github.com/ej52/proxmox-scripts/blob/main/lxc/nginx-proxy-manager/install/debian.sh` and uninstall whatever the script is installing.

It looks like it is also moving sone services. I am afraid that turning nginx off will break stuff, but i did not test is yet.

**Comment by CalebJamesStevens** [comment]
Still not working on debian 

```
[error] Downloading NPM v.tar.gz
/tmp/npm_install.sh: line 113: 'wget $WGETOPT -c $NPMURL/archive/v$_latest_version.tar.gz -O - | tar -xz'

unexpected end of file
Child returned status 1
exiting now
```

**Comment by CalebJamesStevens** [comment]
Update: I forked @gragragrab and it does not work, fails at line 113

**Comment by cyberdork33** [comment]
Yes, now that both patches have been merged. The scripts in this repo should not exhibit this issue anymore.
