### ISSUE TITLE
How to upgrade NPM?

### ISSUE THREAD

**Issue by netstx** [ej52/proxmox-scripts#9]
Hi @ej52, thanks for sharing these scripts, they are really useful. I used your setup.sh to install npm 2.8.0 on an alpine lxc container that I created manually on proxmox. Do you have any feedback on the recommended way to upgrade npm to 2.8.1 for example?

**Comment by ej52** [comment]
@netstx The script should install/upgrade the latest version of npm if you run the setup again.

`wget --no-cache -qO - https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/setup.sh | sh`

**Comment by netstx** [comment]
Thanks!

**Comment by Oujiii** [comment]
@ej52 Quick question, didn't wanna raise a new issue for that. Whenever NPM is updated I can just run the install script and it will pull the latest version?

Thank you.

**Comment by netstx** [comment]
@Oujiii looking at the code, it looks like that's what it does

**Comment by Oujiii** [comment]
@netstx I thought the same by looking into the code, but wanted to confirm just to be sure.

**Comment by ej52** [comment]
> @ej52 Quick question, didn't wanna raise a new issue for that. Whenever NPM is updated I can just run the install script and it will pull the latest version?
> 
> Thank you.

@Oujiii that is correct
