### ISSUE TITLE
Error download template on Proxmox 7.2

### ISSUE THREAD

**Issue by Giorgio-Banani** [ej52/proxmox-scripts#95]
**Script**
nginx-proxy-manager

**Describe the bug**
installation scipt fails here:
[info] Updating LXC template list...
[info] Downloading LXC template...
[error] 143 NULL: _storage_type=$(pvesm status -storage $_storage 2>/dev/null | awk 'NR>1 {print $2}')

![image](https://user-images.githubusercontent.com/104979449/197333613-049c785b-f48e-4083-b709-c3f0f126e13f.png)

**System info:**
 - Proxmox Version: 7.2

**Comment by hayou** [comment]
Try : 
`curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s -- --cores 2 --disksize 10G --bridge vmbr1 --id 140 --memory 1024 --storage local`

**Comment by H4nSolo** [comment]
https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/install --> Result: Not found

**Comment by Alanimdeo** [comment]
Do you installed Proxmox with ZFS? Try using `--storage local-zfs`

Commands should be like:
```sh
curl -sL https://raw.githubusercontent.com/ej52/proxmox/main/lxc/nginx-proxy-manager/create.sh | bash -s -- --storage local-zfs
```

**Comment by ParaVirtual** [comment]
> https://raw.githubusercontent.com/ej52/proxmox-scripts/main/lxc/nginx-proxy-manager/install --> Result: Not found

That's the crux of this specific issue, there's a bad URL or a incorrectly constructed URL in the create script, which causes it to fail.
